---
title: "Data Cleaning"
author: "Flannery McNair"
date: "2026-03-18"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(here)
library(tidyverse)
library(ggplot2)
library(lubridate)
library(ggpubr)
library(sf)
```

Uploading Data
```{r}
SVI_2022 <- read_csv(here("California_county_SVI_2022.csv"))
SVI_2020 <- read_csv(here("California_county_SVI_2020.csv"))
SVI_2018 <- read_csv(here("California_county_SVI_2018.csv"))
SVI_2016 <- read_csv(here("California_county_SVI_2016.csv"))
asthma <- read_csv((here("current-asthma-prevalence-by-county-2015_2022.csv")))
AQI_2022 <- read_csv(here("daily_aqi_by_county_2022.csv"))
AQI_2020 <- read_csv(here("daily_aqi_by_county_2020.csv"))
AQI_2018 <- read_csv(here("daily_aqi_by_county_2018.csv"))
AQI_2016 <- read_csv(here("daily_aqi_by_county_2016.csv"))
```

Cleaning SVI Data
```{r}
SVI_2022_clean <- SVI_2022 %>%
  subset(select = -c(STATE, ST_ABBR, ST, LOCATION)) %>%
  select(-starts_with("M_")) %>%
  select(-starts_with("MP_")) %>%
  select(-starts_with("F_"))
SVI_2022_clean$COUNTY <- gsub(" County", "", SVI_2022_clean$COUNTY)

SVI_2020_clean <- SVI_2020 %>%
  subset(select = -c(STATE, ST_ABBR, ST, LOCATION)) %>%
  select(-starts_with("M_")) %>%
  select(-starts_with("MP_")) %>%
  select(-starts_with("F_"))
SVI_2020_clean$COUNTY <- gsub(" County", "", SVI_2020_clean$COUNTY)

SVI_2018_clean <- SVI_2018 %>%
  subset(select = -c(STATE, ST_ABBR, ST, LOCATION)) %>%
  select(-starts_with("M_")) %>%
  select(-starts_with("MP_")) %>%
  select(-starts_with("F_"))
SVI_2018_clean$COUNTY <- gsub(" County", "", SVI_2018_clean$COUNTY)

SVI_2016_clean <- SVI_2016 %>%
  subset(select = -c(STATE, ST_ABBR, ST, LOCATION)) %>%
  select(-starts_with("M_")) %>%
  select(-starts_with("MP_")) %>%
  select(-starts_with("F_"))
SVI_2016_clean$COUNTY <- gsub(" County", "", SVI_2016_clean$COUNTY)
```

Cleaning Asthma data
```{r}
asthma_clean <- asthma %>%
  filter(`AGE GROUP` == "All ages")

years <- sapply(strsplit(asthma_clean$YEARS, "-"), `[`, 2)

asthma_clean <- asthma_clean %>%
  mutate(YEARS = years) %>%
  select(c(COUNTY, YEARS, `CURRENT PREVALENCE`, `95% CONFIDENCE INTERVAL`))
```

```{r}
AQI_2022$Date <- as.Date((AQI_2022$Date))
AQI_2022_clean <- AQI_2022 %>%
  filter(`State Name` == "California") %>%
  aggregate(AQI ~ `county Name`, FUN = "mean") %>%
  rename(COUNTY = `county Name`)

AQI_2020$Date <- as.Date((AQI_2020$Date))
AQI_2020_clean <- AQI_2020 %>%
  filter(`State Name` == "California") %>%
  aggregate(AQI ~ `county Name`, FUN = "mean") %>%
  rename(COUNTY = `county Name`)

AQI_2018$Date <- as.Date((AQI_2018$Date))
AQI_2018_clean <- AQI_2018 %>%
  filter(`State Name` == "California") %>%
  aggregate(AQI ~ `county Name`, FUN = "mean") %>%
  rename(COUNTY = `county Name`)

AQI_2016$Date <- as.Date((AQI_2016$Date))
AQI_2016_clean <- AQI_2016 %>%
  filter(`State Name` == "California") %>%
  aggregate(AQI ~ `county Name`, FUN = "mean") %>%
  rename(COUNTY = `county Name`)
```

Combining SVI and Asthma data
```{r}
asthma_2016 <- asthma_clean %>%
  filter(YEARS == "2016")

data_2016 <- inner_join(AQI_2016_clean, asthma_2016, by = "COUNTY")
data_2016_SVI <- inner_join(data_2016, SVI_2016_clean, by = "COUNTY")

asthma_2018 <- asthma_clean %>%
  filter(YEARS == "2018")

data_2018 <- inner_join(AQI_2018_clean, asthma_2018, by = "COUNTY")
data_2018_SVI <- inner_join(data_2018, SVI_2018_clean, by = "COUNTY")

asthma_2020 <- asthma_clean %>%
  filter(YEARS == "2020")

data_2020 <- inner_join(AQI_2020_clean, asthma_2020, by = "COUNTY")
data_2020_SVI <- inner_join(data_2020, SVI_2020_clean, by = "COUNTY")

asthma_2022 <- asthma_clean %>%
  filter(YEARS == "2022")

data_2022 <- inner_join(AQI_2022_clean, asthma_2022, by = "COUNTY")
data_2022_SVI <- inner_join(data_2022, SVI_2022_clean, by = "COUNTY")
```

Plotting AQI vs asthma prevalence
```{r}
plot_2016 <- ggplot(data_2016, aes(AQI, `CURRENT PREVALENCE`)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(y = "Asthma Prevalence (%)", 
       title = "AQI vs Asthma Prevalence by California County in 2016")

plot_2016

mlm.2 <- lm(data_2016$AQI ~ data_2016$`CURRENT PREVALENCE`)
summary(mlm.2)

plot_2018 <- ggplot(data_2018, aes(AQI, `CURRENT PREVALENCE`)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  stat_cor(aes(label = after_stat(rr.label))) + 
  labs(y = "Asthma Prevalence (%)", 
       title = "AQI vs Asthma Prevalence by California County in 2018")

plot_2018

plot_2020 <- ggplot(data_2020, aes(AQI, `CURRENT PREVALENCE`)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(y = "Asthma Prevalence (%)", 
       title = "AQI vs Asthma Prevalence by California County in 2020")

plot_2020

plot_2022 <- ggplot(data_2022, aes(AQI, `CURRENT PREVALENCE`)) +
  geom_point() + 
  geom_smooth(method = "lm") + 
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(y = "Asthma Prevalence (%)", 
       title = "AQI vs Asthma Prevalence by California County in 2022")

plot_2022
```

Plotting AQI and SVI metrics
```{r}
plot_2020_SVI <- ggplot(data_2020_SVI, aes(AQI, E_POV150)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  stat_cor(aes(label = after_stat(rr.label)))

plot_2020_SVI

plot_2020_RPL <- ggplot(data_2020_SVI, aes(AQI, RPL_THEME3)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  stat_cor(aes(label = after_stat(rr.label)))

plot_2020_RPL
```

Combine data together
```{r}
combined_data <- bind_rows(
  data_2016_SVI %>% mutate(Year = 2016),
  data_2018_SVI %>% mutate(Year = 2018),
  data_2020_SVI %>% mutate(Year = 2020),
  data_2022_SVI %>% mutate(Year = 2022)
)
```

Plot of current prevalence and aqi across years 
```{r}
combined_plot <- ggplot(combined_data, aes(AQI, `CURRENT PREVALENCE`, 
                                           color = factor(Year))) + geom_point()
combined_plot
```

#### DON'T RUN THIS CODE (will not work lol)
```{r}
fires <- st_read("~/Downloads/California_Historic_Fire_Perimeters_-6273763535668926275")

head(fires)

fires$ALARM_DATE <- as.Date(fires$ALARM_DATE)

fires_clean <- fires %>%
  subset(select= -c(STATE, AGENCY, INC_NUM, C_METHOD, OBJECTIVE, COMMENTS,
                    COMPLEX_NA, IRWINID, FIRE_NUM, COMPLEX_ID)) %>%
  filter(YEAR_ == "2022" | YEAR_ == "2020" | YEAR_ == "2018" | YEAR_ == "2016")

cali_counties <- st_read("~/Downloads/ca_counties/CA_Counties.shp")

occurrences_with_county <- st_join(
  fires_clean,
  cali_counties,
  join = st_intersects
)

write_csv(occurrences_with_county, here("Fires_per_county.csv"))
```

Load fire data
```{r}
county_fires <- read_csv(here("Fires_per_county.csv"))
county_fires_clean <- county_fires %>%
  select(c(YEAR_, UNIT_ID, FIRE_NAME, ALARM_DATE, CONT_DATE, GIS_ACRES, DECADES, 
           GEOID, NAME, ALAND, AWATER, Shape_Leng, Shape_Area, geometry))
```

Combining and cleaning fire data with AQI
```{r}
fires_2022 <- county_fires %>%
  filter(YEAR_ == "2022")

fires_2022_counts <- as.data.frame(count(fires_2022, NAME)) %>%
  rename(COUNTY = NAME)

fires_aqi_2022 <- full_join(data_2022, fires_2022_counts, by = "COUNTY") %>%
  drop_na()

fires_2016 <- county_fires %>%
  filter(YEAR_ == "2016")

fires_2016_counts <- as.data.frame(count(fires_2016, NAME)) %>%
  rename(COUNTY = NAME)

fires_aqi_2016 <- full_join(data_2016, fires_2016_counts, by = "COUNTY")
```


Plot fires vs AQI and asthma
```{r}
fire_plot <- ggplot(fires_aqi_2022, aes(x=COUNTY, y=n)) + 
  geom_bar(stat = "identity", fill = "red") + 
  geom_point(data = fires_aqi_2022, aes(x = COUNTY, y=AQI*0.4), 
             color = "blue") + 
  scale_y_continuous(name = "Fire Counts", 
                     sec.axis = sec_axis(~ . / 0.4, name = "AQI")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + 
  labs(title = "Fire Counts and AQI per county in 2022", 
       subtitle = "California")
  
fire_plot

fire_plot_asthma <- ggplot(fires_aqi_2022, aes(x=COUNTY, y=n)) + 
  geom_bar(stat = "identity", fill = "red") + 
  geom_point(data = fires_aqi_2022, aes(x = COUNTY, y=`CURRENT PREVALENCE`), 
             color = "blue") + 
  scale_y_continuous(name = "Fires Counts", 
                     sec.axis = sec_axis(~ . / 0.4, name = "Asthma Prevalence")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + 
  labs(title = "Fire Counts and Asthma per county in 2022", 
       subtitle = "California")
  
fire_plot_asthma

fire_plot_2016 <- ggplot(fires_aqi_2016, aes(x=COUNTY, y=n)) + 
  geom_bar(stat = "identity") + 
  geom_point(data = fires_aqi_2016, aes(x = COUNTY, y=AQI*0.3)) + 
  scale_y_continuous(name = "Fires Counts", 
                     sec.axis = sec_axis(~ . / 0.3, name = "AQI")) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) + 
  labs(title = "Fire Counts and AQI per County in 2016")
  
fire_plot_2016
```

